<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1> ILM </h1>
<b>название трека: </b> ${product.title}<br>
<b>исполнитель: </b> ${product.author}<br>
<b>альбом: </b> ${product.album}<br>
<b>платформа: </b> ${product.platform}<br>
<b>дата выпуска: </b> ${product.releasedate}<br>
<b>кол-во прослушиваний: </b> ${product.listenerscnt}<br>
</body>
</html>